route:
  group_by: [Alertname]
  # Send all notifications to me.
  receiver: email-me

receivers:
- name: email-me
  email_configs:
  - to: 
    from: 
    smarthost: smtp.gmail.com:587
    auth_username: "abc@gmail.com"
    auth_identity: "abc@gmail.com"
    auth_password: "abc"
